Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\N1_Gaming\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
TypeError: save_Account_details() takes 0 positional arguments but 1 was given
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 898, in save_Account_details
    print(i)
UnboundLocalError: local variable 'i' referenced before assignment
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 904, in save_Account_details
    date_instance=DateModel.objects.get(date=target_date)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
api.models.DateModel.DoesNotExist: DateModel matching query does not exist.
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 898, in save_Account_details
    time_instance=TimeEntryModel.objects.get(date=date_instance,Time=time)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
api.models.TimeEntryModel.DoesNotExist: TimeEntryModel matching query does not exist.
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 910, in save_Account_details
    gplay = UserGame.objects.filter(tsn_entry=Tsn_instance, game_name=game_name)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\fields\related_lookups.py", line 168, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 337, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 911, in save_Account_details
    gplay = UserGame.objects.filter(tsn_entry=Tsn_instance, game_name=game_name)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\fields\related_lookups.py", line 168, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 337, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 911, in save_Account_details
    gplay = UserGame.objects.filter(tsn_entry=Tsn_instance, game_name=game_name)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\fields\related_lookups.py", line 168, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 337, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 911, in save_Account_details
    gplay = UserGame.objects.filter(tsn_entry=Tsn_instance)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\fields\related_lookups.py", line 168, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\lookups.py", line 337, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 938, in save_Account_details
    return render(request,'abc.htm')
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: abc.htm
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /acc
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 938, in save_Account_details
    return render(request,'abc.htm')
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: abc.htm
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\N1_Gaming\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\N1_Gaming\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /recentResult
Internal Server Error: /userlogin
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 375, in user_login
    user_data=CustomUser.objects.get(username=username)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
api.models.CustomUser.DoesNotExist: CustomUser matching query does not exist.
Internal Server Error: /userlogin
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 375, in user_login
    user_data=CustomUser.objects.get(username=username)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
api.models.CustomUser.DoesNotExist: CustomUser matching query does not exist.
Unauthorized: /userlogin
Unauthorized: /userlogin
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /sres
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
TypeError: Save_result_earnpoint() takes 0 positional arguments but 1 was given
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sres
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "api_timeentrymodel_pkey"
DETAIL:  Key (id)=(14) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 974, in Save_result_earnpoint
    time_entry.save()
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "api_timeentrymodel_pkey"
DETAIL:  Key (id)=(14) already exists.

E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\N1_Gaming\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sres
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\N1-Gaming\N1_Gaming\api\views.py", line 1064, in Save_result_earnpoint
    return JsonResponse('Result saved successfully')
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\http\response.py", line 684, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
E:\N1-Gaming\N1_Gaming\N1_Gaming\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\api\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\N1_Gaming\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\N1-Gaming\N1_Gaming\N1_Gaming\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\N1_Gaming_backend\api\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /showAccount
Internal Server Error: /showAccount
Traceback (most recent call last):
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\gprin\AppData\Roaming\Python\Python310\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\N1_Gaming_backend\api\views.py", line 669, in show_Account_date
    data = json.loads(request.body)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Watching for file changes with StatReloader
Method Not Allowed: /reprintSlip/A102XNT1706867644949
D:\N1_Gaming_backend\api\views.py changed, reloading.
Watching for file changes with StatReloader
D:\N1_Gaming_backend\api\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
